wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1675024063.290767
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.9
      6: 4.26.0
      8:
      - 5
always_save_checkpoint:
  desc: null
  value: true
backend:
  desc: null
  value: nccl
batch_size:
  desc: null
  value: 1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
block_size:
  desc: null
  value: 512
compile:
  desc: null
  value: false
dataset:
  desc: null
  value: violence
decay_lr:
  desc: null
  value: false
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.2
dtype:
  desc: null
  value: bfloat16
eval_interval:
  desc: null
  value: 200
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
init_from:
  desc: null
  value: gpt2-xl
learning_rate:
  desc: null
  value: 1.0e-05
log_interval:
  desc: null
  value: 1
lr_decay_iters:
  desc: null
  value: 600000
max_iters:
  desc: null
  value: 10000
min_lr:
  desc: null
  value: 6.0e-05
n_embd:
  desc: null
  value: 768
n_head:
  desc: null
  value: 12
n_layer:
  desc: null
  value: 12
out_dir:
  desc: null
  value: out-violence
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: violence
wandb_run_name:
  desc: null
  value: ft-1675024030.071716
warmup_iters:
  desc: null
  value: 2000
weight_decay:
  desc: null
  value: 0.01
